import React from 'react';
import Head from 'next/head'

const HeadSematic = () => {
  return (
    <Head>
      <title>Descovery Task</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
  </Head>
  );
};

export default HeadSematic;